#!/bin/sh -e

if [ -z "$2" ] ; then
	echo "Destdir not given"
	exit 1
fi

if [ ! -d "$2" ] ; then
	echo "$2 is not a directory"
	exit 1
fi

#destdir="`(cd $2 ;pwd)`" 
destdir="$2" 

if [ -d "$1" ] ; then
	cd "$1"
	name="`basename $1`"
	tarfile="$name.tar"
	if [ ! -f "$tarfile" ] ; then
		echo "$1 not found"
		exit 1
	fi
elif [ -f "$1" ] ; then
	if [ "${1##*.}" != "tar" ] ; then
		echo "$1 is not a tar file"
		exit 1
	fi
	cd "`dirname "$1"`"
	tarfile=`basename $1`
	name="${tarfile%.*}"
else
	echo "$1 not found"
	exit 1
fi

find . -name "*.tar" -print0 | xargs -0 -I@ install -D "@" "$destdir/@"
